eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://username:password@localhost:8761}/eureka/
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
zuul:
  ignored-services: '*'
  routes:
    neuropsi-oauth-service:
      path: /auth/**
      serviceId: neuropsi-oauth-service
    neuropsi-record-service:
      path: /api/record/**
      serviceId: neuropsi-record-service
      stripPrefix: false
  sensitive-headers:
    - Cookie
    - Set-Cookie
ribbon:
  eager-load:
    enabled: false
security:
  oauth2:
    resource:
      jwt:
        keyValue: ${PASSWORD:password}