server:
  port: ${PORT:8762}
spring:
  application:
    name: neuropsi-zuul-service
  security:
    user:
      name: ${USERNAME:username}
      password: ${PASSWORD:password}
  profiles:
    active: ${PROFILE:dev}